on:
  push:
  workflow_dispatch:
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-22.08
      options: --privileged
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Restore cache
        id: cache
        uses: actions/cache/restore@v3
        with:
          path: .flatpak-builder
          key: 64gram-flatpak

      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.1
        with:
          bundle: 64gram.flatpak
          manifest-path: org.telegram.desktop.yml
          cache: false

      - name: Save cache
        id: cache-save
        uses: actions/cache/save@v3
        if: always()
        with:
          path: .flatpak-builder
          key: ${{ steps.cache.outputs.cache-primary-key }}
